# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: zImPatrick
          template: classic
          base: header, activity
          config_timezone: Europe/Vienna

          # WakaTime
          plugin_wakatime: yes
          plugin_wakatime_days: 30
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: public
          plugin_wakatime_sections: editors, time, languages, 
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: current
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
