# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: zImPatrick
          template: classic
          base: header, activity
          config_timezone: Europe/Vienna
          
          # Music Plugin
          plugin_music: yes
          plugin_music_limit: 4
          plugin_music_mode: top
          plugin_music_played_at: yes
          plugin_music_provider: lastfm
          plugin_music_time_range: medium
          plugin_music_top_type: tracks
          plugin_music_user: zImPatrick
          plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
